### ISSUE TITLE
Windows 10 - running app results in nothing happening

### ISSUE THREAD

**Issue by CaseyLabs** [bulwarkid/bulwark-issues#2]
Hi there,

I just tried running Bulwark on Windows 10:

- Installation went fine
 
- Desktop shortcut is created. 

- Launching the app prompts for Admin privileges

But after that, nothing happens... no GUI launch or error messages.

Any way I can help diagnose this issue? I've encountered it on two different Win10 machines.

**Comment by cmdli** [comment]
I was able to reproduce this issue, it looks like the WebView2 that Bulwark Passkey relies on wasn't automatically installed on Windows 10 like it is on Windows 11. I just release a new version on https://bulwark.id that should fix this issue, could you try downloading that version and seeing if it works? Thank you for the report!

**Comment by CaseyLabs** [comment]
That did the trick, thank you!

I encountered another possible bug: when I tried to use the "Use Local-Only Vault" option, it gave the following error:

"No new passphrase specified"

![Untitled](https://user-images.githubusercontent.com/4674433/206030825-478d0d82-417f-444d-be38-cf6d22cfafaa.png)

Any ideas on this one? Thanks again for all of your work here.

**Comment by cmdli** [comment]
Ah! Yes, I reproduced that issue as well and fixed it in (yet another) version on bulwark.id. I don't normally use the local-only mode, so I went through and made sure it works end to end. I apologize for having to redownload it, I should also have a one-click update solution soon-ish.

Thank you so much for trying it out!

**Comment by CaseyLabs** [comment]
That did the trick, local vault works now with the latest version. Awesome, can't wait to take this for a spin, thanks for all the help Chris!
